/* SE CREA LA BASE DE DATOS PARA EL SISTEMA CICLOSOFT */
CREATE DATABASE CICLOSOFT
GO 
USE CICLOSOFT --DROP TABLE CICLOSOFT

--=======================================================================================>
/* SE CREA LA TABLA DE USUARIOS ESTA ALAMCENARA LOS USUARIOS ADMINISTRADORES DEL NEGOCIO*/
--=======================================================================================>

CREATE TABLE USERS 
(
	IDUSER				BINARY(16) NOT NULL,	-- LLAVE PRIMARIA DE LA TABLA 
	NAME				VARCHAR(45) NOT NULL,	-- NOMBRE DEL USUARIO 
	LASTNAME			VARCHAR(45)NOT NULL,	-- APELLIDO DEL USUARIO
	PERMODPRODUCT		CHAR(1) NOT NULL,		-- PERMISO PARA EDITAR,CREAR Y BORRAR PRODUCTOS 
	PERORDER			CHAR(1) NOT NULL,		-- PERMISO PARA APROBAR LOS PEDIDOS
	PERENTRY			CHAR(1) NOT NULL,		-- PERMISO PARA CREAR ENTRADAS, MODIFICARLAS Y ANULARLAS
	PERINVOICE			CHAR(1)NOT NULL,		-- PERMISO PARA CREAR FACTURAS CUANDO LOS CLIENTES COMPRAN EN LA TIENDA FISICAMENTE
	CODEUSUAR			VARCHAR(8)NOT NULL,		-- CODIGO DE USUARIO, CON ESTE SE LOGEARA EN EL SISTEMA
	PASSWORD			VARCHAR(15)NOT NULL,	-- COPNTRASEÑA PARA EL LOGUEO 
	STATUSUSER			CHAR(1)NOT NULL,		-- EN ESTE CAMPO SE ALMACENARA EL ESTADO DEL USUARIO, 'A'CTIVO | 'I'NACTIVO
	UPDATETIMESTAMP		DATETIME NOT NULL,		-- CAMPO DE AUDITORIA PARA SABER LA FECHA Y HORA DE CREACION O MODIFICACIÓN DEL REGISTRO EN LÑA TABLA 
	STATUS				CHAR(1)					-- EN ESTE CAMPO SE ALMACENARA EL ESTADO DEL REGISTRO, 'C'READO | 'M'ODIFICADO
)
-- SE CREA LA LLAVE PRIMARIA DE LA TABLA USERS 
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (IDUSER)

--SE CREA RESTRICCION PARA LOS CAMPOS DE PERMISOS, ESTOS SOLO PUEDEN RECIBIR LOS VALORES 'S' O 'N'
ALTER TABLE USERS ADD CONSTRAINT C1_PERMODPRODUCT CHECK (PERMODPRODUCT IN ('S','N'))
GO
ALTER TABLE USERS ADD CONSTRAINT C2_PERORDER CHECK (PERORDER IN ('S','N'))
GO
ALTER TABLE USERS ADD CONSTRAINT C3_PERENTRY CHECK (PERENTRY IN ('S','N'))
GO
ALTER TABLE USERS ADD CONSTRAINT C4_PERINVOICE CHECK (PERINVOICE IN ('S','N'))

-- SE CREA RESTRICCION PARA EL CAMPO DEL ESTADO DEL USUARIO 
ALTER TABLE USERS ADD CONSTRAINT C5_STATUSUSER CHECK (STATUSUSER IN ('S','N'))

-- SE CREA RESTRICCIÓN PARA EL CAMPO DEL ESTADO DEL REGISTRO EN LA TABLA 
ALTER TABLE USERS ADD CONSTRAINT C5_STATUS CHECK (STATUS IN ('C','M'))

--=======================================================================================>
/*	SE CREA LA TABLA DONDE SE ALMACENARAN LOS TIPOS DE PRODUCTOS						*/
--=======================================================================================>
CREATE TABLE TYPEPRODUCT
(
	IDTYPEPRODUCT			BINARY(16) NOT NULL,		--	CODIGO UNICO DE CADA REGISTRO, LLAVE PRIMARIA DE LA TABLA
	REFERENCETYPE			VARCHAR(10)NOT NULL,		--	CODIGO QUE EL USUARIO CONOCE.
	NAMETYPEPRODUCT			VARCHAR(45) NOT NULL,		--	NOMBRE DE LA CATEGORIA DEL PRODUCTO
	IDUSER					BINARY(16) NOT NULL,		--	USUARIO QUE CREA ! MODIFICA EL REGISTRO LLAVE FORANEA DE LA TABLA DE USUARIOS
	UPDATETIMESTAMP			DATETIME NOT NULL,			--	FECHA DE CREACION O MODIFICACIÓN DEL REGISTRO
	STATUS					CHAR(1) NOT NULL			--	ESTADO DEL REGISTRO, 'C'REAO | 'M'ODIFICADO
)

-- SE CREA LLAVE PRIMARIA DE LA TABLA 
ALTER TABLE TYPEPRODUCT ADD CONSTRAINT PK_TYPEPRODUCT PRIMARY KEY (IDTYPEPRODUCT)

-- SE CREA LLAVE FORANEA DE LA TABLA DE USUARIOS
ALTER TABLE TYPEPRODUCT ADD CONSTRAINT FK1_IDUSER FOREIGN KEY (IDUSER) REFERENCES USERS(IDUSER)

-- SE CREA RESTRICCION PARA EL CAMPO STATUS ESTE SOLO ALMACENA 'C' | 'M'
ALTER TABLE TYPEPRODUCT ADD CONSTRAINT C1_STATUS CHECK (STATUS IN ('C','M'))

--=======================================================================================>
/*	SE CREA LA TABLA DONDE SE ALMACENARAN LOS PRODUCTOS									*/
--=======================================================================================>
CREATE TABLE PRODUCTS 
(
	IDPRODUCT			BINARY(16)NOT NULL,			--	CODIGO UNICO DEL PRODUCTO, LLAVE PRIMARIA DE LA TABLA
	NAMEPRODUCT			VARCHAR(45)NOT NULL,		--	NOMBRE DEL PRODUCTO
	MANIVA				CHAR(1) NOT NULL,			--	SI EL PRODUCTO MANEJA IVA 'S' O 'N'
	REFERENCE			VARCHAR(20) NOT NULL,		--	REFERENCIA DEL PRODUCTO, CODIGO CON EL CUAL EL USUARIO LO RECONOCE
	PORIVA				DECIMAL(3,2) NOT NULL,		--	PORCENTAJE DEL IVA
	PRICE				DECIMAL(28,4) NOT NULL,		--	PRECIO DEL PRODUCTO
	DESCRIPTION			VARCHAR(150) NOT NULL,		--	DESCRIPCION DEL PRODUCTO
	IDTYPEPRODUCT		BINARY(16) NOT NULL,		--	TIPO DE PRODUCTO LLAVE FORANEA DE LA TABLA TYPEPRODUCT
	STATUSPRODUCT		CHAR(1)NOT NULL,			--	ESTADO DEL PRODUCTO 'A'CTIVO | 'I'NACTIVO
	IDUSER				BINARY(16) NOT NULL,		--	USUARIO QUE CREA O MODIFICA LLAVE FORANEA CON LA TABLA DE USUARIOS
	UPDATETIMESTAMP		DATETIME NOT NULL,			--	FECHA Y HORA DE LA MODIFICACIÓN DEL REGISTRO
	STATUS				CHAR(1)NOT NULL				--  ESTADO DEL REGIUSTRO 'C'READO | 'M'ODIFICADO
)

-- SE CREA LLAVE PRIMARIA DE LA TABLA PRODUCTS
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (IDPRODUCT)

-- SE CREA LLAVE FORANEA DE LA TABLA TYPEPRODUCT
ALTER TABLE PRODUCTS ADD CONSTRAINT FK1_IDTYPEPRODUCT FOREIGN KEY (IDTYPEPRODUCT) REFERENCES TYPEPRODUCT(IDTYPEPRODUCT)

--SE CREA LLAVE FORANEA DE LA TABLA USERS 
ALTER TABLE PRODUCTS ADD CONSTRAINT FK2_IDUSER FOREIGN KEY (IDUSER) REFERENCES USERS(IDUSER)

-- SE CREA RESTRICCION PARA EL CAMPO STATUSPRODUCT SOLO PUEDE ALMACENAR 'A' | 'I'
ALTER TABLE PRODUCTS ADD CONSTRAINT C1_STATUSPRODUCT CHECK (STATUSPRODUCT IN ('A','I'))

-- SE CREA RESTRICCIÓN PARA EL CAMPO STATUS SOLO ALMACENARÁ 'C' | 'M'
ALTER TABLE PRODUCTS ADD CONSTRAINT C2_STATUS CHECK (STATUS IN ('C','M')) 